### ISSUE TITLE
ANE not showing any usage on M1 Pro

### ISSUE THREAD

**Issue by johnalanwoods** [tlkh/asitop#14]
Hi, 

I have an M1 Pro, and I've been trying to get `asitop` to show ANE usage.
However, even when executing ML based tasks, such as: https://github.com/asus4/depth-prediction-macOS

The ANE usage is pegged to 0/0w.

Any idea why?

**Comment by johnalanwoods** [comment]
I got it to show up using Photos to do some edits, not sure why CoreML apps don't seem to use it during execution? - maybe the engine is used only for creation of the models

**Comment by tlkh** [comment]
CoreML is very opaque about how it decides to use the ANE. There are a lot of instances where it simply does not use the ANE and there is nothing configurable about that. 

If you use the webcam, it should always be using the ANE for some kind of processing, so you can use that to check!

**Comment by johnalanwoods** [comment]
Thanks! You’re absolutely right. 

Weird about how CoreML doesn’t choose to use the ANE sometimes. 

Appreciate the info.
