### ISSUE TITLE
Can I contribute to it?

### ISSUE THREAD

**Issue by TienTim** [tlkh/asitop#24]
<img width="1342" alt="Screen Shot 2022-03-29 at 11 25 00 PM" src="https://user-images.githubusercontent.com/32588948/160647390-f4a008a8-67f1-48c8-a9d5-c0ff380a12ec.png">
I added feature that show each core usage.

**Comment by tlkh** [comment]
Hi, that's pretty cool, I think it would be nice if it could be enabled with a flag upon startup (eg `asitop --show-cores`) or something. Would you be able to try and implement something like that?

**Comment by TienTim** [comment]
Yes, I will implement it. A flag will be `asitop --show-cores` with default value is false.

**Comment by tlkh** [comment]
You can follow this guide here to open a pull request https://opensource.com/article/19/7/create-pull-request-github

**Comment by tlkh** [comment]
Thanks for you work. Give me some time to test it first. But now you have your own fork, feel free to treat that as your own project as well!. I do not intend to "monopolize" asitop in any way, feel free to run with your own ideas etc.
