### ISSUE TITLE
KeyError: 'hw.perflevel1.logicalcpu'

### ISSUE THREAD

**Issue by paul-nameless** [tlkh/asitop#4]
Hello again,

Thanks for merging the fix with powermetrics.

Unfortunately now I am facing another error, maybe that's also because of the different OS versions...
Here is a traceback:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/asitop", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/asitop/asitop.py", line 71, in main
    soc_info_dict = get_soc_info()
  File "/opt/homebrew/lib/python3.9/site-packages/asitop/utils.py", line 136, in get_soc_info
    "e_core_count": core_counts_dict["hw.perflevel1.logicalcpu"],
KeyError: 'hw.perflevel1.logicalcpu'
```
core_counts_dict calls get_core_counts()
and it calls `sysctl -a | grep hw.perflevel`
which returns nothing on BigSur at least

Here is the output that I could get:
```
~ > sudo sysctl -a | grep hw.p 
hw.packages: 1
hw.pagesize: 16384
hw.pagesize32: 16384
hw.physicalcpu: 8
hw.physicalcpu_max: 8
```

**Comment by tlkh** [comment]
Yeah probably due to OS difference. That’s used to check for the number of E core and P core. I can just catch the error and disable the check I guess.

**Comment by tlkh** [comment]
Put in a quick and dirty fix, now it will run but the core counts will show up as "?".

**Comment by paul-nameless** [comment]
Looks good to me, thanks!
