### ISSUE TITLE
Asitop does not work

### ISSUE THREAD

**Issue by KKIT-98** [tlkh/asitop#40]
Why is asitop installed through PIP3 but cannot be executed? Zsh: command not found: show asitop

**Comment by BitesPotatoBacks** [comment]
@KKIT-98 for some reason, pip does not install asitop into a dir that is in zsh's PATH, (such as `usr/bin/`), which is why zsh doesn't know that asitop exists. Usually, asitop is installed in `/Library/Python/.../bin`. For now you could add that dir to your `.zshrc` file.

**Comment by KKIT-98** [comment]
> @KKIT-98出于某种原因，pip不会将asitop安装到zsh的PATH中的dir中（例如`usr/bin/`），这就是为什么zsh不知道asitop存在的原因。通常，asitop安装在`/Library/Python/.../bin`。目前，您可以将该dir添加到您的`.zshrc`文件中。
OK, it has been solved. Thank you very much!
