### ISSUE TITLE
Not working with macOS Ventura

### ISSUE THREAD

**Issue by johnnynunez** [tlkh/asitop#43]
powermetrics: unrecognized sampler: bandwidth

M1 MAX

**Comment by BitesPotatoBacks** [comment]
This problem has also occurred at issue #41...

**Comment by jerjer1223** [comment]
not working for me either

**Comment by mmatook** [comment]
Same here with the public release version of Ventura 13.0 on an M1 Max.

**Comment by splicedwdm** [comment]
Would appreciate instructions for a fix also.

**Comment by november1118** [comment]
Same here.

2020 MBP M1

**Comment by zfyao666** [comment]
Same here.
macOS Ventura
2020 MBA M1

**Comment by tzakharko** [comment]
It seems Apple has removed DRAM statistics in powertools, which is why asitop breaks.

**Comment by zfyao666** [comment]
> It seems Apple has removed DRAM statistics in powermetrics, which is why asitop breaks. They also changed the wording (it's now 'total power' instead of 'package power', which kind of makes sense as I suspect that powermetrics never really reported package power on Apple Silicon).

So we need to wait the developer change the code or wording in asitop?

**Comment by tzakharko** [comment]
From what I see there is already a patch, they are just working out the details

https://github.com/tlkh/asitop/pull/44

**Comment by zfyao666** [comment]
OK, thanks for your comments. I will follow up on this patch.

**Comment by sbstndalton** [comment]
> powermetrics: unrecognized sampler: bandwidth
> 
> M1 MAX

Same here, M2 MacBook Air, Ventura 13.0 Public Release

**Comment by johnnynunez** [comment]
download https://github.com/SuperKenVery/asitop zip
pip install asitop-main.zip

**Comment by puzweee** [comment]
> 

Hi John, 

Thanks for your kind support for this project.

Would you kindly tell if there is any difference between this solution and simply upgrading to next released version.

Thanks

**Comment by mikumi** [comment]
@johnnynunez 

> download https://github.com/SuperKenVery/asitop zip pip install asitop-main.zip

Thanks a lot for providing this! Unfortunately I'm not very familiar with neither powermetrics nor python, so I can't really debug. But I have noticed something interesting: it seems the package power can be lower than the CPU power, which shouldn't be possible I guess?

For demonstration purposes I ran Cinebench and captured the `asitop` output in the following screenshot:

<img width="1792" alt="Screenshot 2022-11-03 at 5 30 21 PM" src="https://user-images.githubusercontent.com/1838667/199688186-95010827-ece2-4eec-b5b7-f33b8d9ea828.png">

**Comment by vladkens** [comment]
@johnnynunez thanks a lot.

An even simpler way to install a temporary solution for MacOS Ventura:

```
pip uninstall -y asitop
pip install git+https://github.com/SuperKenVery/asitop.git
```

**Comment by sbstndalton** [comment]
> @johnnynunez
> 
> > download https://github.com/SuperKenVery/asitop zip pip install asitop-main.zip
> 
> Thanks a lot for providing this! Unfortunately I'm not very familiar with neither powermetrics nor python, so I can't really debug. But I have noticed something interesting: it seems the package power can be lower than the CPU power, which shouldn't be possible I guess?
> 
> For demonstration purposes I ran Cinebench and captured the `asitop` output in the following screenshot:
> 
> <img alt="Screenshot 2022-11-03 at 5 30 21 PM" width="1792" src="https://user-images.githubusercontent.com/1838667/199688186-95010827-ece2-4eec-b5b7-f33b8d9ea828.png">

How did you make it look like that? I'm not very versed in the usage besides the basic terminal commands.

**Comment by mikumi** [comment]
> How did you make it look like that? I'm not very versed in the usage besides the basic terminal commands.

That's [tmux](https://github.com/tmux/tmux/wiki), running three terminals with `asitop` at the top left, `top` at the top right, and `htop` at the bottom.

**Comment by molekulek** [comment]
ASITOP - Performance monitoring CLI tool for Apple Silicon
You can update ASITOP by running `pip install asitop --upgrade`
Get help at `https://github.com/tlkh/asitop`
P.S. You are recommended to run ASITOP with `sudo asitop`


[1/3] Loading ASITOP


[2/3] Starting powermetrics process


[3/3] Waiting for first reading...

powermetrics: unrecognized sampler: bandwidth
-------------

Still networking :(

**Comment by usc2019** [comment]
> > @johnnynunez
> > > download https://github.com/SuperKenVery/asitop zip pip install asitop-main.zip
> > 
> > 
> > Thanks a lot for providing this! Unfortunately I'm not very familiar with neither powermetrics nor python, so I can't really debug. But I have noticed something interesting: it seems the package power can be lower than the CPU power, which shouldn't be possible I guess?
> > For demonstration purposes I ran Cinebench and captured the `asitop` output in the following screenshot:
> > <img alt="Screenshot 2022-11-03 at 5 30 21 PM" width="1792" src="https://user-images.githubusercontent.com/1838667/199688186-95010827-ece2-4eec-b5b7-f33b8d9ea828.png">
> 
> How did you make it look like that? I'm not very versed in the usage besides the basic terminal commands.

I have the same question,How did you do it？

**Comment by mikumi** [comment]
> I have the same question,How did you do it？

Please see my [reply](https://github.com/tlkh/asitop/issues/43#issuecomment-1304567431) above 🙃

**Comment by johnnynunez** [comment]
working now
