### ISSUE TITLE
Not working on MBP11,3

### ISSUE THREAD

**Issue by joshauh46** [tlkh/asitop#5]
Hi, 
I'm getting an error when I try to start it 

Model: MBP11,3 

```
powermetrics: unrecognized sampler: bandwidth
^CTraceback (most recent call last):
  File "/usr/local/bin/asitop", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/asitop/asitop.py", line 109, in main
    ready = get_reading()
  File "/usr/local/lib/python3.9/site-packages/asitop/asitop.py", line 105, in get_reading
    time.sleep(wait)
```

**Comment by tlkh** [comment]
Is this an Intel Mac? This app does not work on Intel Mac.

**Comment by sunipkm** [comment]
Seems the issue has come back on macOS Ventura (MBP 18,3) [M1 Pro].

**Comment by aaronkogan** [comment]
> Seems the issue has come back on macOS Ventura (MBP 18,3) [M1 Pro].

True, on M2 Air the same problem after update macOS

**Comment by BitesPotatoBacks** [comment]
@sunipkm @aaronkogan This is due to the bandwidth sampler being removed from Powermetrics in Ventura (See #41)

**Comment by elgs** [comment]
Why is this issue closed without a solution?

**Comment by BitesPotatoBacks** [comment]
@elgs the issue was previously closed due to it being an Intel related problem (asitop only supports Apple Silicon). This same issue is now affecting Apple Silicon, but has not yet been reopened by the maintainer.

**Comment by tongclement** [comment]
this is still an issue
